# Generated by Django 4.2.5 on 2024-04-06 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.commentpost'),
        ),
    ]
